#!/usr/bin/env pwsh
# =============================================================================
# generate_version.ps1 — Git-based version stamp for NSIS installers
#
# Usage:
#   .\generate_version.ps1            # auto-detect from git tag, fallback 3.1.1
#   .\generate_version.ps1 -Force 3.2.0  # force a specific version
#
# Output: version.nsh  (included by all .nsi installer scripts)
# =============================================================================

param(
    [string]$Force    = "",        # override: pass "3.2.0" to force that version
    [string]$Fallback = "3.1.1"   # used when no git tags exist yet
)

$ErrorActionPreference = "SilentlyContinue"

# ---------------------------------------------------------------------------
# 1. Determine version string
# ---------------------------------------------------------------------------
if ($Force -ne "") {
    $version = $Force
    Write-Host "generate_version: forced to $version"
} else {
    try {
        $version = (git describe --tags --abbrev=0 2>$null).Trim()
        if ($LASTEXITCODE -ne 0 -or -not $version) { throw "no tag" }
        $version = $version -replace '^[vV]', ''   # strip leading v/V
        Write-Host "generate_version: git tag -> $version"
    } catch {
        $version = $Fallback
        Write-Host "generate_version: no git tag found, using fallback $version"
    }
}

# ---------------------------------------------------------------------------
# 2. Parse into components (pad to at least 4 parts)
# ---------------------------------------------------------------------------
$parts  = ($version.Split('.')) + @("0","0","0","0")
$major  = $parts[0].Trim()
$minor  = $parts[1].Trim()
$patch  = $parts[2].Trim()
$build  = "0"          # NSIS VIProductVersion requires 4 parts; keep build at 0

# ---------------------------------------------------------------------------
# 3. Write version.nsh
# ---------------------------------------------------------------------------
$outPath = Join-Path $PSScriptRoot "version.nsh"

$content = @"
; =============================================================================
; version.nsh  —  Auto-generated by generate_version.ps1
; DO NOT EDIT MANUALLY.  Run:  .\generate_version.ps1  to refresh.
; =============================================================================
!define VERSION         "$version"
!define VERSION_MAJOR   $major
!define VERSION_MINOR   $minor
!define VERSION_PATCH   $patch
!define VERSION_BUILD   $build
!define VERSION_QUAD    "$major.$minor.$patch.$build"
"@

[System.IO.File]::WriteAllText($outPath, $content, [System.Text.Encoding]::UTF8)
Write-Host "generate_version: wrote $outPath  (version $version)"
