; =============================================================================
; version.nsh  â€”  Auto-generated by generate_version.ps1
; DO NOT EDIT MANUALLY.  Run:  .\generate_version.ps1  to refresh.
; =============================================================================
!define VERSION         "3.1.1"
!define VERSION_MAJOR   3
!define VERSION_MINOR   1
!define VERSION_PATCH   1
!define VERSION_BUILD   0
!define VERSION_QUAD    "3.1.1.0"