<?php
/**
 * mixer.php — Virtual Mixer Console
 * Mcaster1 DSP Encoder — Phase MX-1
 *
 * Horizontal channel-strip mixing board interface for controlling all encoder
 * slots simultaneously. Each strip has a VU meter, vertical fader, pan knob,
 * mute/solo buttons, and status indicator.
 */
define('MC1_BOOT', true);
require_once __DIR__ . '/app/inc/auth.php';
require_once __DIR__ . '/app/inc/db.php';
require_once __DIR__ . '/app/inc/user_auth.php';

if (!mc1_is_authed()) {
    http_response_code(302);
    header('Location: /login');
    return;
}

$page_title = 'Mixer Console';
$active_nav = 'mixer';
$use_charts = false;

require_once __DIR__ . '/app/inc/header.php';
?>

<link rel="stylesheet" href="/css/mixer.css">
<link rel="stylesheet" href="/css/mixer-skins.css">

<div class="sec-hdr">
  <div class="sec-title">
    <i class="fa-solid fa-sliders" style="color:var(--teal);margin-right:8px"></i>Virtual Mixer Console
  </div>
  <div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap">
    <span id="mixer-api-status" class="badge badge-gray">API: --</span>
    <span id="mixer-ch-count" class="badge badge-teal">0 Channels</span>
  </div>
</div>

<!-- Toolbar: config name, save, reset -->
<div class="mixer-toolbar">
  <div class="mixer-toolbar-left">
    <label style="font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:.05em">Config:</label>
    <input type="text" class="mixer-config-name" id="mixer-config-name" value="Default" placeholder="Config name" maxlength="128">
    <button class="btn btn-primary btn-sm" onclick="window._mixer.saveConfig()" title="Save mixer configuration">
      <i class="fa-solid fa-floppy-disk"></i> Save
    </button>
    <button class="btn btn-secondary btn-sm" onclick="window._mixer.resetAll()" title="Reset all faders to unity">
      <i class="fa-solid fa-rotate-left"></i> Reset
    </button>
    <div style="position:relative;display:inline-block">
      <button class="btn btn-secondary btn-sm" id="btn-presets-toggle" onclick="togglePresetsPanel()" title="Mixer presets">
        <i class="fa-solid fa-bookmark"></i> Presets
      </button>
      <div id="mixer-presets-panel" style="display:none;position:absolute;top:100%;left:0;z-index:200;min-width:320px;margin-top:4px;background:var(--card);border:1px solid var(--border);border-radius:var(--radius);box-shadow:0 8px 32px rgba(0,0,0,.4);padding:12px">
        <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:10px">
          <span style="font-size:.85rem;font-weight:700;color:var(--text)"><i class="fa-solid fa-bookmark" style="color:var(--teal);margin-right:6px"></i>Saved Presets</span>
          <button style="background:none;border:none;color:var(--text-dim);cursor:pointer;font-size:14px" onclick="togglePresetsPanel()">&times;</button>
        </div>
        <div id="mixer-presets-list" style="max-height:300px;overflow-y:auto;margin-bottom:10px">
          <div style="color:var(--muted);font-size:.8rem;text-align:center;padding:10px">Loading...</div>
        </div>
        <div style="display:flex;gap:6px">
          <button class="btn btn-primary btn-xs" style="flex:1" onclick="saveAsPreset()">
            <i class="fa-solid fa-plus"></i> Save As New Preset
          </button>
        </div>
      </div>
    </div>
  </div>
  <div class="mixer-toolbar-right">
    <label style="font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:.05em">Skin:</label>
    <select class="mixer-skin-select" id="mixer-skin-select" onchange="window._mixer && window._mixer.setSkin(this.value)" title="Mixer console skin">
      <option value="broadcast_dark">Broadcast Dark</option>
      <option value="studio_warm">Studio Warm</option>
      <option value="live_neon">Live Neon</option>
      <option value="vintage_analog">Vintage Analog</option>
      <option value="military_tactical">Tactical</option>
      <option value="arctic_clean">Arctic Clean</option>
    </select>
    <button class="btn btn-secondary btn-sm" id="btn-link-dash" onclick="window.location.href='/dashboard.php'" title="Go to Dashboard">
      <i class="fa-solid fa-gauge"></i> Dashboard
    </button>
    <button class="btn btn-secondary btn-sm" id="btn-link-enc" onclick="window.location.href='/encoders.php'" title="Go to Encoders">
      <i class="fa-solid fa-tower-broadcast"></i> Encoders
    </button>
  </div>
</div>

<!-- Mixer console surface -->
<div class="mixer-surface" id="mixer-surface" data-mixer-skin="broadcast_dark">
  <div class="mixer-channels" id="mixer-ch-wrap">
    <!-- Channel strips are dynamically generated by mixer-console.js -->
    <div style="display:flex;align-items:center;justify-content:center;width:100%;min-height:400px;color:var(--muted);font-size:13px">
      <div class="spinner" style="margin-right:10px"></div> Loading encoder slots...
    </div>
  </div>
</div>

<!-- Keyboard shortcuts help -->
<div class="card" style="margin-top:14px">
  <div class="card-hdr">
    <div class="card-title"><i class="fa-solid fa-keyboard fa-fw"></i> Controls</div>
  </div>
  <div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:10px;font-size:12px;color:var(--text-dim)">
    <div>
      <span style="color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.05em">Fader</span><br>
      Click &amp; drag fader cap, or click track to jump
    </div>
    <div>
      <span style="color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.05em">Keyboard</span><br>
      Click a channel, then <kbd style="background:var(--bg2);border:1px solid var(--border);border-radius:3px;padding:1px 5px;font-size:11px">&uarr;</kbd>/<kbd style="background:var(--bg2);border:1px solid var(--border);border-radius:3px;padding:1px 5px;font-size:11px">&darr;</kbd> to adjust by 5%
    </div>
    <div>
      <span style="color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.05em">Pan</span><br>
      Click &amp; drag pan knob. Double-click to center
    </div>
    <div>
      <span style="color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.05em">Mute / Solo</span><br>
      <span style="color:var(--red);font-weight:700">M</span> mutes channel (volume=0).
      <span style="color:#f59e0b;font-weight:700">S</span> solos (dims others visually)
    </div>
  </div>
</div>

<script src="/js/webgl-viz.js"></script>
<script src="/js/mixer-console.js"></script>
<script>
(function() {
  document.addEventListener('DOMContentLoaded', function() {
    window._mixer = new MixerConsole();
    window._mixer.init('mixer-ch-wrap');

    // Update channel count badge and API status on poll
    var origPoll = window._mixer._poll.bind(window._mixer);
    var wrappedPoll = function() {
      origPoll();
      // After poll, update badges
      setTimeout(function() {
        var count = Object.keys(window._mixer.channels).length;
        var badge = document.getElementById('mixer-ch-count');
        if (badge) badge.textContent = count + ' Channel' + (count !== 1 ? 's' : '');

        var apiEl = document.getElementById('mixer-api-status');
        if (apiEl) {
          var hasLive = false;
          for (var sid in window._mixer.channels) {
            if (window._mixer.channels[sid].state === 'live') { hasLive = true; break; }
          }
          if (count > 0) {
            apiEl.textContent = hasLive ? 'API: Online (Live)' : 'API: Online';
            apiEl.className = 'badge ' + (hasLive ? 'badge-green' : 'badge-teal');
          }
        }
      }, 500);
    };
    window._mixer._poll = wrappedPoll;

    // Close presets panel on outside click
    document.addEventListener('click', function(e) {
      var panel = document.getElementById('mixer-presets-panel');
      var btn   = document.getElementById('btn-presets-toggle');
      if (panel && panel.style.display !== 'none' && !panel.contains(e.target) && !btn.contains(e.target)) {
        panel.style.display = 'none';
      }
    });
  });
})();

/* ══════════════════════════════════════════════════════════════════════════
 * Mixer Presets
 * ══════════════════════════════════════════════════════════════════════════ */
function togglePresetsPanel() {
    var panel = document.getElementById('mixer-presets-panel');
    if (panel.style.display === 'none') {
        panel.style.display = 'block';
        loadMixerPresets();
    } else {
        panel.style.display = 'none';
    }
}

function mxEsc(s) {
    return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

function loadMixerPresets() {
    mc1Api('GET', '/api/v1/mixer/presets').then(function(d) {
        if (!d || !d.ok) return;
        var list = document.getElementById('mixer-presets-list');
        var presets = d.presets || [];
        if (presets.length === 0) {
            list.innerHTML = '<div style="color:var(--muted);font-size:.8rem;text-align:center;padding:10px">No saved presets yet</div>';
            return;
        }
        var html = '';
        presets.forEach(function(p) {
            html += '<div style="display:flex;align-items:center;justify-content:space-between;padding:8px 10px;background:rgba(255,255,255,.03);border:1px solid var(--border);border-radius:4px;margin-bottom:6px">'
                + '<div>'
                + '  <div style="font-size:.85rem;font-weight:600;color:var(--text)">' + mxEsc(p.config_name) + '</div>'
                + '  <div style="font-size:.65rem;color:var(--muted)">Vol: ' + Math.round(p.master_volume * 100) + '%</div>'
                + '</div>'
                + '<div style="display:flex;gap:4px">'
                + '  <button class="btn btn-xs btn-primary" onclick="loadMixerPreset(' + p.id + ')"><i class="fa-solid fa-download"></i> Load</button>'
                + '  <button class="btn btn-xs btn-danger" onclick="deleteMixerPreset(' + p.id + ')"><i class="fa-solid fa-trash"></i></button>'
                + '</div>'
                + '</div>';
        });
        list.innerHTML = html;
    }).catch(function() {
        document.getElementById('mixer-presets-list').innerHTML = '<div style="color:var(--red);font-size:.8rem;text-align:center;padding:10px">API unreachable</div>';
    });
}

function loadMixerPreset(id) {
    mc1Api('GET', '/api/v1/mixer/presets/' + id).then(function(d) {
        if (!d || !d.ok) { mc1Toast('Load failed', 'err'); return; }
        // Apply to mixer
        if (!window._mixer) return;
        if (d.config_name) {
            window._mixer.configName = d.config_name;
            window._mixer.configId = d.config_id;
            var nameInput = document.getElementById('mixer-config-name');
            if (nameInput) nameInput.value = d.config_name;
        }
        if (d.master_volume !== undefined) {
            window._mixer.master.volume = d.master_volume;
            window._mixer._updateFaderVisual('master', d.master_volume);
            window._mixer._sendVolume('master', d.master_volume);
        }
        if (d.channel_json && Array.isArray(d.channel_json)) {
            d.channel_json.forEach(function(saved) {
                var sid = saved.slot_id;
                if (window._mixer.channels[sid]) {
                    if (saved.volume !== undefined) {
                        window._mixer.channels[sid].volume = saved.volume;
                        window._mixer._updateFaderVisual(sid, saved.volume);
                        window._mixer._sendVolume(sid, saved.volume);
                    }
                    if (saved.pan !== undefined) {
                        window._mixer.channels[sid].pan = saved.pan;
                        window._mixer._updatePanVisual(sid, saved.pan);
                    }
                    if (saved.muted !== undefined) window._mixer.channels[sid].muted = saved.muted;
                    if (saved.solo !== undefined) window._mixer.channels[sid].solo = saved.solo;
                }
            });
        }
        mc1Toast('Preset loaded: ' + d.config_name, 'ok');
        window._mixer._render();
        togglePresetsPanel();
    }).catch(function() { mc1Toast('API unreachable', 'err'); });
}

function deleteMixerPreset(id) {
    if (!confirm('Delete this preset?')) return;
    mc1Api('DELETE', '/api/v1/mixer/presets/' + id).then(function(d) {
        if (d && d.ok) {
            mc1Toast('Preset deleted', 'ok');
            loadMixerPresets();
        } else {
            mc1Toast('Delete failed', 'err');
        }
    }).catch(function() { mc1Toast('API unreachable', 'err'); });
}

function saveAsPreset() {
    var name = prompt('Preset name:');
    if (!name || !name.trim()) return;
    name = name.trim();

    if (!window._mixer) return;
    var channelArr = [];
    for (var sid in window._mixer.channels) {
        var ch = window._mixer.channels[sid];
        channelArr.push({
            slot_id: parseInt(sid),
            volume: ch.volume,
            pan: ch.pan || 0,
            muted: !!ch.muted,
            solo: !!ch.solo
        });
    }

    mc1Api('POST', '/api/v1/mixer/presets', {
        config_name: name,
        master_volume: window._mixer.master.volume,
        channel_json: channelArr
    }).then(function(d) {
        if (d && d.ok) {
            mc1Toast('Preset saved: ' + name, 'ok');
            loadMixerPresets();
        } else {
            mc1Toast('Save failed', 'err');
        }
    }).catch(function() { mc1Toast('API unreachable', 'err'); });
}
</script>

<?php require_once __DIR__ . '/app/inc/footer.php'; ?>
